Prevent myself from running setup scripts as root
When I am setting up a new laptop, I sometimes accidentally run one of
my setup scripts as root, which creates files in my home directory that
are root-owned and that cause problems later when they cannot be read or
modified.  These `if` clauses should protect me.

diff --git a/bin/,setup b/bin/,setup
--- a/bin/,setup
+++ b/bin/,setup
@@ -7,6 +7,12 @@
 
 set -e
 
+if [ "$(id -u)" = "0" ]
+then
+    echo 'Error: this script should not be run as root' >&2
+    exit 1
+fi
+
 case "$1" in
 "ag" )
     V=0.30.0
diff --git a/bin/,setup-home-usr b/bin/,setup-home-usr
--- a/bin/,setup-home-usr
+++ b/bin/,setup-home-usr
@@ -4,6 +4,12 @@
 
 set -e
 
+if [ "$(id -u)" = "0" ]
+then
+    echo 'Error: this script should not be run as root' >&2
+    exit 1
+fi
+
 SYSPY=/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
 if [ ! -x $SYSPY ]; then
     SYSPY=/usr/bin/python2.7
diff --git a/bin/,setup-ubuntu b/bin/,setup-ubuntu
--- a/bin/,setup-ubuntu
+++ b/bin/,setup-ubuntu
@@ -2,6 +2,12 @@
 
 set -e
 
+if [ "$(id -u)" = "0" ]
+then
+    echo 'Error: this script should not be run as root' >&2
+    exit 1
+fi
+
 sudo apt-get update
 
 # Avoid "perl" locale errors and the "locale" error:
