Protect ,up against two failure modes

diff --git a/bin/,up b/bin/,up
--- a/bin/,up
+++ b/bin/,up
@@ -13,6 +13,14 @@ then
     exit
 fi
 
+# Make sure an SSH key is available before attempting git operations.
+
+if ! ssh-add -l >/dev/null
+then
+    echo 'Error: please ssh-add an SSH key'
+    exit 1
+fi
+
 # Update my home directory setup to make sure I have the most recent
 # versions of everything.
 
@@ -50,7 +58,7 @@ then
     xdg-mime default google-chrome.desktop x-scheme-handler/https
 fi
 
-if ! [ -f .emacs.d/aspell-huge ]
+if [ -f ~/.emacs.d/SETUP-spell.sh ] && ! [ -f .emacs.d/aspell-huge ]
 then
     pushd .emacs.d
     ./SETUP-spell.sh
