Bail out with an error on unrecognized hardware

diff --git a/bin/,vga-1024 b/bin/,vga-1024
--- a/bin/,vga-1024
+++ b/bin/,vga-1024
@@ -2,4 +2,9 @@
 
 LVDS=$(xrandr | grep '^LVDS.* connected ' | awk '{print $1}')
 VGA=$(xrandr | grep '^VGA' | awk '{print $1}')
+if [ -z "$LVDS" -o -z "$VGA" ]
+then
+    echo 'Cannot find devices!'
+    exit 1
+fi
 xrandr --output $VGA --same-as $LVDS --mode 1024x768 --rate 60.0
